name: POI
true: 
  pull_request: 
    branches: 
      - master
    paths: 
      - apis/poi/**
      - .github/workflows/poi.yml
  push: 
    branches: 
      - master
    paths: 
      - apis/poi/**
      - .github/workflows/poi.yml
env: 
  build_name: POI
  docker_path: apis/poi/web
  poi_path: apis/poi/**
  prod_url: "https://openhackxv61mxh2poi.azurewebsites.net"
  registry: docker.pkg.github.com
  repository: hattan/openhack-devops-team-gh/api-poi
  resource_group: openhackxv61mxh2rg
  staging_url: "https://openhackxv61mxh2poi-staging.azurewebsites.net"
  webapp_name: openhackxv61mxh2poi
jobs: 
  build_and_test: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        name: "Setup .NET Core"
        uses: actions/setup-dotnet@v1
      - 
        name: "Add Code Coverage Tools"
        run: "dotnet add package coverlet.msbuild"
        working-directory: apis/poi/tests/UnitTests
      - 
        name: "Install dependencies"
        run: "dotnet restore apis/poi/web/*.csproj"
      - 
        name: ".NET Build Web"
        run: "dotnet build --configuration Release --no-restore apis/poi/web/*.csproj"
      - 
        name: ".NET Build Unit Tests"
        run: "dotnet build --configuration Release apis/poi/tests/UnitTests/UnitTests.csproj"
      - 
        name: ".NET Test"
        run: "dotnet test --no-restore --verbosity normal apis/poi/tests/UnitTests  /p:CollectCoverage=true /p:CoverletOutput=lcov/ /p:CoverletOutputFormat=lcov​"
      - 
        name: Coveralls
        uses: coverallsapp/github-action@master
        with: 
          base-path: apis/poi
          flag-name: Unit
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          path-to-lcov: apis/poi/tests/UnitTests/lcov/coverage.info
